# Generated by Django 2.2.10 on 2020-03-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Binfo', '0002_blood_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='blood',
            name='City',
            field=models.CharField(default='Null', max_length=30),
            preserve_default=False,
        ),
    ]
